name: Java PR build (gradle)

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # pin@v4
      - uses: gradle/wrapper-validation-action@b5418f5a58f5fd2eb486dd7efb368fe7be7eae45 # pin@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # pin@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Build with Gradle
        run: ./gradlew build
